apiVersion: v1
kind: Service
metadata:
   name: back-svc
   labels:
      app: back-svc
spec:
   type: ClusterIP
   ports:
      - port: {{ .Values.port }}
        targetPort: {{ .Values.tpart }}
   selector:
         component: back

